import string
import re
import nltk
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import svm
from sklearn.feature_selection import mutual_info_classif
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.corpus import stopwords
from imblearn.over_sampling import SMOTE

# cleaning
def cleaning(teks):
    link_pattern = r'(?:https?://)?(?:www\.)?(?:Tsel\.me/internet|indosat.com\/(kampunggajah|iddpromo)|panpizza\.co\.id|indosatooredoo.com\/|bit\.ly\/|blj\.co\/|indogetjob.com\/|loop\.co\.id|tri\.co\.id|telkomsel.com|indosat.com/transstudiobgd|www.indosatooredoo.com/freedom|berrybenka.com\/|nagamas-cell.com|lazada\.co\.id\/|zalora\.co\.id\/|My\.XL\.co\.id|[a-zA-Z0-9-]+\.blogspot\.com|berkah1000poin\.wix\.com/prize|indracell.com|promobni46.tk|3care2016.com|blanja.com|cahayatourtravel.com|mhegatravel.com|buatijazahs1.wordpress.com|tsel.me/as|surya-travel.jimdo.com|murahituim3.com\/|citiling-travel.com|WWW.3-INFO.WEBNODE.COM|bit.ly/tentangCIGNA|jayabet4.com|@loop_id|gebyarINDOSATpoinplus.weebly.com|t-selpoinhadiah.jimdo.com|Http://www/yusiwa.com|hquarters\.co\.id|tricare.jimdo.com|berkat-isiulang-pulsa.webs.com|[a-zA-Z0-9-]+\.webs\.com|inforesmi3care.com|[a-zA-Z0-9-]+\.jimdo\.com|gebeyar-3care.tk|[a-zA-Z0-9-]+\.weebly\.com|bit.ly/tentangCIGNA|Www.|[a-zA-Z0-9-]+\.blogspot\.co\.idbrotogel6.com|programisiulang3care.tkÂ|megaprimatama.com|www.info|Www.3care16.blogspot.com|Www.tricare16.blogspot.com|[a-zA-Z0-9-]+\.blogspot\.co\.id|brotogel6.com|www.info|undian2016bri.blogspot.co.id|callcenterbankbri.blogspot.co.id|hadiahbankbri2016.blogspot.co.id|programundiantricare-2015.blogspot.co.id|gebyarmtronik.tk|sampoernatbk.co.nf|\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b|genuineoil.co.id|hadiahmtronik-2016.tk|bnitaplus46.tk|Bonus3tri.com|http//www.gebyar-trichampions.jimdo.com.|Asia-travel.com|gebyarhadiah2016.com|tricareindonesia.com|infohadiahtricare.com|pt-tricare.co|telkomsell.jimdo|telkomselpoin-777.pusku.com|id.tri.webnode.com|http//tri-2016.webnode.com/|http//info-undian3.webnode.com/|my-tri8.webnode.com|http//info-3careindonesia.com/|pusat-tricare.com|gebyar-tricare.com|hadiah-tricare.com|cekhadiahmtronik2016.ga|gebyartricare.co.vu|blogspot.com|tri-2015.webnode.com|undianbri.co.vu|WWW.TOKOBAGUSPHONE.COM|jayabb.com|top100-celluler.com|lion-airtravel.com.|https?://\S+)'
    teks = re.sub(link_pattern, ' ', teks)
    teks  = re.compile('[%s]' % re.escape(string.punctuation)).sub(' ', teks)
    teks  = re.sub(r'\d', ' ',teks)
    teks = re.sub(r'xxx|xv|wk|hmm|wkwk|hehehe|wkwkwk|nyaah|hehe|oh|ooh|tuh nah|yahh|€|™|â||loh', ' ', teks)
    return teks

def case_folding(teks):
    teks = teks.lower()
    return teks

# normalization
kamus_normalisasi = {
      "app"         : "aplikasi",
      "dpt"         :	"dapat",
      "g"           :	"giga",
      "mnt"         :	"menit",
      "hr"          :	"hari",
      "gb"          : "gigabyte",
      "rp"          :	"rupiah",
      "sd"          :	"sampai dengan",
      "nov"         :	"november",
      "sk"          :	"syarat ketentuan",
      "plg"         :	"pelanggan",
      "yth"         :	"yang terhormat",
      "apps"        :	"aplikasi",
      "utk"         :	"untuk",
      "hub"         :	"hubungi",
      "kb"          :	"kilobyte",
      "skb"         :	"syarat ketentuan berlaku",
      "rb"          :	"ribu",
      "dg"          :	"dengan",
      "sjk"         :	"sejak",
      "aug"         :	"agustus",
      "sept"        :	"september",
      "dgn"         :	"dengan",
      "unreg"       : "membatalkan registrasi",
      "hrga"        : "harga",
      "tkn"         :	"tekan",
      "jt"          :	"juta",
      "dptkan"      :	"dapatkan",
      "mb"          :	"megabyte",
      "sblm"        : "sebelum",
      "tariff"      :	"tarif",
      "skrg"        : "sekarang",
      "tlh"         :	"telah",
      "hadih"       :	"hadiah",
      "gb"          :	"gigabyte",
      "s"           : "syarat",
      "k"           : "ketentuan",
      "vchr"        :	"voucher",
      "feb"         :	"februari",
      "msh"         :	"masih",
      "internetas"  :	"internetan",
      "jl"          :	"jalan",
      "no"          :	"nomor",
      "kpd"         : "kepada",
      "u"	          : "untuk",
      "min"         :	"minimal",
      "dapetkan"    :	"dapatkan",
      "nelp"        :	"nelpon",
      "nmr"         :	"nomor",
      "hny"         :	"hanya",
      "yg"          :	"yang",
      "jan"         :	"januari",
      "hayu"        :	"ayo",
      "rerencengan" :	"teman",
      "sareng"      :	"bersama",
      "buktikeun"   :	"buktikan",
      "nyalira"     :	"sendiri",
      "dll"         :	"dan lain lain",
      "hg"          :	"harga",
      "dr"          :	"dari",
      "ktk"         :	"ketik",
      "krm"         :	"kirim",
      "disc"        :	"discount",
      "telf"        :	"telfon",
      "agust"       :	"agustus",
      "info"        :	"informasi",
      "tak"         :	"tidak",
      "usah"        :	"perlu",
      "we"          :	"saja",
      "atuh"        :	"lah",
      "smua"        :	"semua",
      "dptkn"       :	"dapatkan",
      "des"         :	"desember",
      "jmlh"        :	"jumlah",
      "agt"         :	"agustus",
      "hatur"       :	"terima",
      "nuhun"       :	"kasih",
      "minimun"     :	"minimum",
      "urang"       :	"orang",
      "ado"         :	"ada",
      "rancak"      :	"keren",
      "kampuang"    :	"kampung",
      "gak"         :	"tidak",
      "sekrang"     :	"sekarang",
      "blanja"      :	"belanja",
      "nrml"        :	"normal",
      "mumpung"     :	"selagi",
      "agsts"       :	"agustus",
      "klyakan"     :	"kelayakan",
      "berstifikat" :	"bersertifikat",
      "platihan"    :	"pelatihan",
      "rekom"       :	"rekomendasi",
      "ph"          :	"perusahaan",
      "hp"          :	"handphone",
      "sbg"         :	"sebagai",
      "tnpa"        :	"tanpa",
      "prlu"        :	"perlu",
      "trima"       :	"terima",
      "telp"        :	"telpon",
      "mendptkan"   :	"mendapatkan",
      "sesame"      :	"sesama",
      "prog"        :	"program",
      "lg"          :	"lagi",
      "dpt"         :	"dapat",
      "bln"         :	"bulan",
      "lgs"         :	"langsung",
      "dptkan"      :	"dapatkan",
      "telp"        :	"telepon",
      "doyan"       :	"suka",
      "slm"         :	"selama",
      "pnwrn"       :	"penawaran",
      "pd"          :	"pada",
      "apps"        :	"aplikasi",
      "ga"          :	"tidak",
      "smuanya"     :	"semuanya",
      "surveu"      :	"survei",
      "jul"         :	"juli",
      "kartuhalo"   :	"kartu halo",
      "yth"         :	"yang terhormat",
      "mal"         :	"malaysia",
      "sin"         :	"singapore",
      "hk"          :	"hongkong",
      "chn"         :	"china",
      "mla"         :	"malaysia",
      "sng"         :	"singapore",
      "hkg"         :	"hongkong",
      "twn"         :	"taiwan",
      "vtm"         :	"vietnam",
      "tlp"	        : "telepon",
      "pkt"         :	"paket",
      "agst"        :	"agustus",
      "ckp"         :	"cukup",
      "hgg"         :	"hingga",
      "tdk"         :	"tidak",
      "tgl"         :	"tanggal",
      "tsb"         :	"tersebut",
      "jgn"         :	"jangan",
      "pcs"         :	"potongan",
      "mar"         :	"maret",
      "bhs"         :	"bahasa",
      "nov"         :	"november",
      "quota"       :	"kuota",
      "ags"         :	"agustus",
      "hrg"         :	"harga",
      "dst"         :	"dan seterusnya",
      "dptkn"       :	"dapatkan",
      "bns"         :	"bonus",
      "dlm"         :	"dalam",
      "pk"          :	"pukul",
      "cs"          :	"layanan pelanggan",
      "tunjukan"    :	"tunjukkan",
      "ckup"        :	"cukup",
      "tahu"        :	"tau",
      "tlh"         :	"telah",
      "trmksh"      :	"terima kasih",
      "jg"          :	"juga",
      "gak"         :	"tidak",
      "mgg"         :	"minggu",
      "byr"         :	"bayar",
      "brminat"     :	"berminat",
      "scond"       :	"barang bekas",
      "brg"         :	"barang",
      "istmwa"      :	"istimewa",
      "sj"          :	"saja",
      "dsini"       :	"disini",
      "mnyediakn"   : "menyediakan",
      "pmain"       :	"pemain",
      "sring"       :	"sering",
      "bisah"       :	"bisa",
      "mbntu"       :	"membantu",
      "jt"          :	"juta",
      "skrg"        :	"sekarang",
      "brg"         :	"barang",
      "hub"         :	"hubungi",
      "ass"         :	"assalamualaikum",
      "sys"         :	"saya",
      "kondisiy"    :	"kondisinya",
      "mrasa"       :	"merasa",
      "bpk"         :	"bapak",
      "tlong"       :	"tolong",
      "dlu"         :	"dulu",
      "an"          :	"atas nama",
      "lt"          :	"lantai",
      "sdh"         :	"sudah",
      "mhubungi"    :	"menghubungi",
      "jd"          :	"jadi",
      "krimkn"      :	"kirimkan",
      "lwt"         :	"lewat",
      "assalamu alaikum"  :	 "assalamualaikum",
      "assalamu alaiqum"  :	 "assalamualaikum",
      "ulsa"        :	"pulsa",
      "tukokno"     :	"isi ulang",
      "ndisek"      :	"isikan",
      "iki"         :	"ini",
      "nmrku"       :	"nomorku",
      "cepet"       :	"cepat",
      "saiki"       :	"sekarang",
      "tak"         :	"aku",
      "enteni"      :	"tunggu",
      "penteng"     :	"penting",
      "msalah"      :	"masalah",
      "aq"          :	"aku",
      "tlpn"        :	"telepon",
      "mndpt"       :	"mendapat",
      "tpilih"      :	"terpilih",
      "sbg"         :	"sebagai",
      "mendpt"      :	"mendapat",
      "dri"         :	"dari",
      "mdptkan"     :	"mendapatkan",
      "sertipikat"  :	"sertivikat",
      "kelik"       :	"klik",
      "klick"       :	"klik",
      "kmi"         :	"kami",
      "inih"        :	"ini",
      "bapa"        :	"bapak",
      "temen"       :	"teman",
      "penring"     :	"penting",
      "rek"         :	"rekening",
      "priode"      :	"periode",
      "trpilih"     :	"terpilih",
      "slma"        :	"selama",
      "dengna"      :	"dengan",
      "krm"         :	"kirim",
      "cp"          :	"contact person",
      "unruk"       :	"untuk",
      "kmu"         :	"kamu",
      "udh"         :	"sudah",
      "n"           :	"sudah",
      "bs"          :	"bisa",
      "th"          :	"tahun",
      "oprator"     :	"operator",
      "mdpt"        :	"mendapat",
      "rbu"         :	"ribu",
      "hsil"        :	"hasil",
      "sbgi"        :	"sebagai",
      "pkl"         :	"pukul",
      "tdftr"       :	"terdaftar",
      "mndptkn"     :	"mendapatkan",
      "slmt"        :	"selamat",
      "tdftar"      :	"terdaftar",
      "pmnang"      :	"pemenang",
      "au"          :	"atau",
      "trimksh"     :	"terima kasih",
      "jk"          :	"jika",
      "rmh"         :	"rumah",
      "pnjam"       :	"pinjam",
      "orng"        :	"orang",
      "tlng"        :	"tolong",
      "bliin"       :	"beliin",
      "pls"         :	"pulsa",
      "nomr"        :	"nomor",
      "msalh"       :	"masalah",
      "karna"       :	"karena",
      "klo"         :	"kalau",
      "lsg"         :	"langsung",
      "ref"         :	"referensi",
      "hg"          :	"hingga",
      "mlm"         :	"malam",
      "ktk"         :	"ketik",
      "ktr"         :	"kantor",
      "bhw"         :	"bahwa",
      "mnghubungi"  :	"menghubungi",
      "trsambung"   :	"tersambung",
      "krn"         :	"karena",
      "ewu"         :	"ribu",
      "km"          :	"kami",
      "dl"          :	"dulu",
      "sdah"        :	"sudah",
      "tpi"         :	"tapi",
      "tdak"        :	"tidak",
      "tks"         :	"thanks",
      "d"           :	"di",
      "sys"         :	"saya",
      "dh"          :	"sudah",
      "meganai"     :	"mengenai",
      "mah"         :	"mama",
      "rbu"         :	"ribu",
      "pangmeserkeun" :	"isikan",
      "heula"       :	"segera",
      "kana"        :	"ke",
      "ieu"         :	"ini",
      "tong"        :	"segera",
      "nuju"        :	"ke",
      "ayeuna"      :	"sekarang",
      "fcopy"       :	"fotokopi",
      "surpai"      :	"survei",
      "lngsng"      :	"langsung",
      "smangat"     :	"semangat",
      "bljr"        :	"belajar",
      "mningkat"    :	"meningkat",
      "shd"         :	"sudah",
      "pribdi"      :	"pribadi",
      "mks"         :	"makasih",
      "tipon"       :	"telpon",
      "menghub"     :	"menghubungi",
      "rekning"     :	"rekening",
      "tbungn"      :	"tabungan",
      "hrus"        :	"harus",
      "gunakn"      :	"gunakan",
      "kmbli"       :	"kembali",
      "sblum"       :	"sebelum",
      "kntor"       :	"kantor",
      "hrap"        :	"harap",
      "pk"	        : "bapak",
      "wallppr"     :	"wallpaper",
      "slh"         :	"salah",
      "bs"          :	"bisa",
      "tuanai"      :	"tunai",
      "slmt"        :	"selamat",
      "sgr"         :	"segera",
      "dri"         :	"dari",
      "sdh"         :	"sudah",
      "ulanag"      :	"ulang",
      "sbg"         :	"sebagai",
      "th"          :	"tahun",
      "mndpt"       :	"mendapat",
      "unt"         :	"unit",
      "slamat"      :	"selamat",
      "mndpt"       :	"mendapat",
      "mendptkn"    :	"mendapatkan",
      "slmt"        :	"selamat",
      "mdpt"        :	"mendapat",
      "slmt"        :	"selamat",
      "mdptkam"     :	"mendapatkan",
      "nomer"       :	"nomor",
      "sbgi"        :	"sebagai",
      "opoerator"   :	"operator",
      "tlah"        :	"telah",
      "jdi"         :	"jadi",
      "lwt"         :	"lewat",
      "trsmbung"    :	"tersambung",
      "jtuh"        :	"jatuh",
      "tnpa"        :	"tanpa",
      "syrt"        :	"syarat",
      "krtu"        :	"kartu",
      "jui"         :	"juli",
      "tk"          :	"terima kasih",
      "notip"       :	"notif",
      "mraih"       :	"meraih",
      "medptkan"    :	"mendapatkan",
      "mslh"        :	"masalah",
      "mhn"         :	"mohon",
      "jkt"         :	"jakarta",
      "pst"         :	"pusat",
      "td"          :	"tadi",
      "belikn"      :	"belikan",
      "pake"        :	"pakai",
      "km"          :	"kamu",
      "yacc"        :	"yah",
      "pswt"        :	"pesawat",
      "hrga"        :	"harga",
      "tks"         :	"thanks",
      "dptkan"      :	"dapatkan",
      "mndptkan"    :	"mendapatkan",
      "terdftr"     :	"terdaftar",
      "mnt"         :	"menit",
      "cekbns"      :	"cek bonus",
      "bns"         :	"bonus",
      "kpd"         : "kepada",
      "lenkap"      :	"lengkap",
      "kntr"        :	"kantor",
      "tdi"         :	"tadi",
      "mlm"         :	"malam",
      "lngsung"     :	"langsung",
      "slmt"        :	"selamat",
      "pmenang"     :	"pemenang",
      "mdpt"        :	"mendapat",
      "slmt"        :	"selamat",
      "almt"        :	"alamat",
      "pmenan"      :	"pemenang",
      "max"         :	"maks",
      "pinj"        :	"pinjam",
      "pemenan"     :	"pemenang",
      "yunit"       :	"unit",
      "ga"          :	"tidak",
      "tlg"         :	"tolong",
      "jgn"         :	"jangan",
      "htl"         :	"hotel",
      "skrg"        :	"sekarang",
      "hbngi"       :	"hubungi",
      "bgi"         :	"bagi",
      "bsedia"      : "bersedia",
      "brencana"    :	"berencana",
      "sbsar"       :	"sebesar",
      "byr"         :	"bayar",
      "tnggu"       :	"tunggu",
      "dkrm"        :	"dikirim",
      "plsa"        :	"pulsa",
      "krim"        :	"kirim",
      "tbs"         :	"tembus",
      "stlh"        :	"setelah",
      "jt"          :	"juta",
      "kluarganya"  :	"keluarganya",
      "nti"         :	"nanti",
      "klau"        :	"kalau",
      "rek"         :	"rekening",
      "trimksi"     :	"terima kasih",
      "trims"       :	"terima kasih",
      "kbrin"       :	"kabarin",
      "norek"       :	"nomor rekening",
      "klau"        :	"kalau",
      "sdah"        :	"sudah",
      "nmor"        :	"nomor",
      "trima"       :	"terima",
      "ksh"         :	"kasih",
      "mjd"         :	"menjadi",
      "gnkan"       :	"gunakan",
      "seda"        :	"sedia",
      "jga"         :	"juga",
      "kg"          :	"kilogram",
      "tlng"        :	"tolong",
      "tmn"         :	"teman",
      "kash"        :	"kasih",
      "nb"          :	"nota bene",
      "bla"         :	"bila",
      "mksh"        :	"makasih",
      "trmks"       :	"terima kasih",
      "trnsfer"     :	"transfer",
      "trmh"        :	"terima",
      "sdh"         :	"sudah",
      "yank"        :	"sayang",
      "baruq"       :	"baru",
      "dl"          :	"dulu",
      "gw"          :	"aku",
      "bget"        :	"banget",
      "krn"         :	"karena",
      "tgguin"      :	"tungguin",
      "yach"        :	"yah",
      "kpd"         :	"kepada",
      "kariyawan"   :	"karyawan",
      "mhub"        :	"menghubungi",
      "ngsih"       :	"ngasih",
      "coklat"      :	"cokelat",
      "tuk"         : "untuk",
      "ang"         :	"angkatan",
      "sebenarny"   :	"sebenarnya",
      "kur"         :	"kurikulum",
      "ato"         :	"atau",
      "mk"          :	"mata kuliah",
      "spt"         :	"seperti",
      "assalam"     :	"assalamualaikum",
      "wibb"        :	"wib",
      "gdg"         :	"gedung",
      "informasiny" :	"informasinya",
      "lab"         :	"laboratorium",
      "matakuliah"  :	"mata kuliah",
      "bkn"         :	"bukan",
      "yaa"         :	"ya",
      "tpi"         :	"tapi",
      "gatau"       :	"tidak tau",
      "msh"         :	"masih",
      "engga"       :	"tidak",
      "udh"         :	"sudah",
      "dipake"      :	"dipakai",
      "dmn"         :	"dimana",
      "tdr"         :	"tidur",
      "gt"          :	"gitu",
      "fb"          :	"facebook",
      "temen"       :	"teman",
      "alesannya"   :	"alasannya",
      "karna"       :	"karena",
      "nyakitin"    :	"sakitin",
      "hape"        :	"handphone",
      "tp"          :	"tapi",
      "usah"        :	"sudah",
      "kaldaluarsa" :	"kedaluwarsa",
      "bapa nya"    : "bapaknya",
      "dah"         :	"sudah",
      "dtg"         :	"datang",
      "agak"        :	"sedikit",
      "ngga"        :	"tidak",
      "pt"          :	"perseroan terbatas",
      "berangkt"    :	"berangkat",
      "besoook"     :	"besok",
      "mo"          : "mau",
      "diem"        :	"diam",
      "lgsg"        :	"langsung",
      "geleh"       :	"geli",
      "sendiiri"    :	"sendiri",
      "dapet"       :	"dapat",
      "gaktau"      :	"tidak tau",
      "yaaa"        :	"ya",
      "bjam"        :	"jam",
      "misal"       :	"misalnya",
      "bener"       :	"benar",
      "trs"         :	"terus",
      "db"          :	"database",
      "akang"       :	"abang",
      "teteh"       :	"kakak",
      "hayuu"       :	"ayo",
      "kakak"       :	"kakak",
      "ditungguuu"  :	"ditunggu",
      "mhsi"        :	"mahasiswa",
      "ilkom"       :	"ilmu komunikasi",
      "ap"          :	"apa",
      "aj"          :	"saja",
      "sp"          :	"semester pendek",
      "ninggalin"   :	"meninggalkan",
      "gaperlu"     :	"tidak perlu",
      "atuhlah"     :	"terserah",
      "bisi"        :	"bisa",
      "naha"        :	"kenapa",
      "aja"         :	"saja",
      "yaaah"       :	"ya",
      "sdg"         :	"sedang",
      "nunggu"      :	"menunggu",
      "waktupenguji" :	"waktu penguji",
      "kudu"        :	"harus",
      "atuh"        :	"lah",
      "ngeh"        :	"sadar",
      "pajuin"      :	"majukan",
      "stuju"       :	"setuju",
      "kagi"        :	"lagi",
      "nyoba"       :	"mencoba",
      "ngejar"      :	"kejar",
      "abis"        :	"habis",
      "gpp"         :	"tidak masalah",
      "berapaa"     :	"berapa",
      "ih"          :	"sih",
      "beu"         :	"mau",
      "ppl"         :	"praktik pengaman lapangan",
      "biasana"     :	"biasanya",
      "bu"          :	"ibu",
      "pak"         :	"bapak",
      "ato"         :	"atau",
      "bgt"         :	"banget",
      "gedorin"     :	"ketuk",
      "byk"         :	"banyak",
      "beres"       :	"selesai",
      "ntr"         :	"nanti",
      "td"          :	"tadi",
      "ktmu"        :	"ketemu",
      "bntr"        :	"bentar",
      "males"       :	"malas",
      "ttd"         :	"tanda tangan",
      "bakal"       :	"akan",
      "kmna"        :	"kemana",
      "bsok"        :	"besok",
      "kmpul"       :	"kumpul",
      "gmna"        :	"bagaimana",
      "gini"        :	"begini",
      "sapa"        :	"siapa",
      "btw"         :	"kebetulan",
      "gaada"       : "tidak ada",
      "gede"        :	"besar",
      "na"          :	"navigasi",
      "tetep"	      : "tetap",
      "bikin"       :	"buat",
      "punten"      :	"maaf",
      "brp"         :	"berapa",
      "nuhun"       :	"terima kasih",
      "sbgai"       :	"sebagai",
      "gapapa"      :	"tidak masalah",
      "sebenernya"  :	"sebenarnya",
      "kang"        :	"bang",
      "sdgkn"       :	"sedangkan",
      "maneh"       :	"kamu",
      "ente"        :	"kamu",
      "jalanken"    :	"jalankan",
      "urg"         :	"aku",
      "soalna"      :	"soalnya",
      "gabungken"   :	"gabungkan",
      "lieur"       :	"lelah",
      "helmkuuuu"   :	"helm aku",
      "selesei"     :	"selesai",
      "blm"         :	"belum",
      "dpn"         :	"depan",
      "yah"         :	"ya",
      "gaaa"        :	"tidak",
      "dooong"      :	"dong",
      "ss"          : "tangkapan layar",
      "bisns"       :	"bisnis",
      "maapin"      :	"maafin",
      "gmana"       :	"bagaimana",
      "kembaliin"   :	"kembalikan",
      "kmr"         :	"kamar",
      "lt"          :	"lantai",
      "dmana"       :	"dimana",
      "nyampe"      :	"sampai",
      "malem"       :	"malam",
      "gusti"       :	"tuhan",
      "ujan"        :	"hujan",
      "namakuuu"    :	"nama aku",
      "luluuus"     :	"lulus",
      "temen"       :	"teman",
      "brati"       :	"berarti",
      "mgrib"       :	"maghrib",
      "ajaaa"       :	"saja",
      "dijmput"     :	"di jemput",
      "brgkt"       :	"berangkat",
      "aya"         :	"ada",
      "meren"       :	"janji",
      "pariksa"     :	"periksa",
      "saha"        : "siapa",
      "kamrin"      :	"kemarin",
      "makasihh"    :	"makasih",
      "kanto"       :	"kantor",
      "gaaais"      :	"teman",
      "dlm"         :	"dalam",
      "kyk"         :	"seperti",
      "nih"         :	"saja",
      "kke"         :	"ke",
      "ulg"         :	"ulang",
      "sekalulian"  :	"sekalian",
      "ap"          :	"apa",
      "gadiabsen"   :	"tidak di absen",
      "lebib"       :	"lebih",
      "da"          :	"saja",
      "kayanya"     :	"sepertinya",
      "dicek"       :	"di cek",
      "pdhl"        :	"padahal",
      "diinvite"    :	"di invite",
      "bapa"        :	"bapak",
      "laaah"       :	"lah",
      "gabawa"      :	"tidak bawa",
      "abis"        :	"habis",
      "yaaa"        :	"ya",
      "bdg"         :	"bandung",
      "gaaak"       :	"tidak",
      "pake"        :	"pakai",
      "pm"          :	"pesan pribadi",
      "ayoook"      :	"ayo",
      "disurvey"    :	"di survei",
      "wktnya"      :	"waktunya",
      "ttg"         :	"tentang",
      "mag"         :	"magnitudo",
      "jun"         :	"juni",
      "lok"         :	"lokasi",
      "km"          :	"kilometer",
      "kep"         :	"kepulauan",
      "kedlmn"      :	"kedalaman",
      "ls"          :	"lintang selatan",
      "bt"          :	"bujur timur",
      "smg"         :	"semoga",
      "trs"         :	"terus",
      "tf"          :	"transfer",
      "inget"       :	"ingat",
      "gtau"        :	"tidak tau",
      "ko"          :	"kenapa",
      "mo"          :	"mau",
      "agus"        :	"agustus",
      "sept"        :	"september",
      "terkahir"    :	"terakhir",
      "singapur"    :	"singapore",
      "taro"        :	"letakkan",
      "dsb"         :	"dan sebagainya",
      "kek"         :	"seperti",
      "iyaaa"       :	"iya",
      "iyaaaa"      :	"iya",
      "ayyuuuukk"   :	"ayo",
      "temaan"      :	"teman",
      "deket"       :	"dekat",
      "gmn"         :	"bagaimana",
      "brpnya"      :	"berapanya",
      "bsk"         :	"besok",
      "kpnnnih"     :	"kapan nih",
      "kekantor"    :	"ke kantor",
      "jd"          :	"jadi",
      "deh"         :	"saja",
      "lbh"         :	"lebih",
      "kdgkan"      :	"terkadang",
      "bbrp"        :	"beberapa",
      "brp"         :	"berapa",
      "kep"         :	"kepulauan",
      "ad"          :	"ada",
      "bandungg"    :	"bandung",
      "blg"         :	"bilang",
      "rame"        :	"ramai",
      "qaqa"        :	"kakak",
      "gituch"      :	"gitu",
      "bntar"       :	"bentar",
      "bts"         :	"batas",
      "trfr"        :	"transfer",
      "yu"          :	"yuk",
      "pdg"         :	"padang",
      "ko"          :	"kok",
      "gtu"         :	"gitu",
      "ngeroko"     :	"merokok",
      "ku"          :	"aku",
      "resto"       :	"restoran",
      "kmren"       :	"kemarin",
      "maaaaaaaaf"  :	"maaf",
      "lupaaa"      :	"lupa",
      "dadi"        :	"tadi",
      "pisaaaan"    :	"banget",
      "bgmana"      :	"bagaimana",
      "kepegat"     : "terjebak",
      "tibatiba"    :	"tiba tiba",
      "jatoh"       :	"jatuh",
      "semuanyaaa"  :	"semuanya",
      "yaaa"        :	"ya",
      "malem"       :	"malam",
      "nanggung"    :	"tanggung",
      "mw"          :	"mau",
      "dblkng"      :	"dibelakang",
      "hdr"         :	"hadir",
      "gaaaa"       :	"tidak",
      "ama"         :	"sama",
      "spt"         :	"seperti",
      "slainya"     :	"selai",
      "mgkin"       :	"mungkin",
      "inpo"        :	"info",
      "hbs"         :	"habis",
      "siaraan"     :	"siaran",
      "lgsg"        :	"langsung",
      "ntar"        :	"bentar",
      "tak"         :	"tidak",
      "maacih"      :	"makasih",
      "mo"          :	"mau",
      "kbtulan"     :	"kebetulan",
      "dsni"        :	"disini",
      "dtggu"       :	"ditunggu",
      "kyknya"      :	"sepertinya",
      "trus"	      : "terus",
      "pesen"       :	"pesan",
      "kmr"         :	"kamar",
      "remed"       :	"remedial",
      "diem"        :	"diam",
      "tuk"         :	"untuk",
      "cmn"         :	"cuma",
      "kau"         :	"kamu",
      "pager"       :	"pagar",
      "ingetin"     :	"ingatin",
      "nanya"       :	"tanya",
      "brrti"       :	"berarti",
      "ijin"        :	"izin",
      "lab"         :	"laboratorium",
      "dkrm"        :	"dikirim",
      "dtgu"        :	"ditunggu",
      "msk"         :	"masuk",
      "kt"          :	"kita",
      "sbelumhya"   :	"sebelumnya",
      "esok"        :	"besok",
      "kalopun"     :	"kalaupun",
      "brngktnya"	  : "berangkatnya",
      "dtng"        :	"datang",
      "bls"         :	"balas",
      "gmna"        :	"bagaimana",
      "bsok"        :	"besok",
      "sdg"         :	"sedangkan",
      "tersrrah"    :	"terserah",
      "okt"         :	"oktober",
      "bhs"         :	"bahasa",
      "tp"          :	"tapi",
      "hdr"         :	"hadir",
      "mmber"       :	"member",
      "bsa"         :	"bisa",
      "mhs"         :	"mahasiswa",
      "klau"        :	"kalau",
      "brgkt"       :	"berangkat",
      "nngk"        :	"tidak",
      "masalh"      :	"masalah",
      "pengen"      :	"mau",
      "chatting"    : "mengobrol",
      "puluhanjt"   : "puluhan juta",
      "setting"     : "pengaturan",
      "hobimu"      : "hobi kamu",
      "tea"         : "teh",
      "flavour"     : "rasa",
      "extra"       : "ekstra",
      "call"        : "telepon",
      "handphone"   : "telepon genggam",
      "x"           : "kali",
      "items"       : "item",
      "download"    : "unduh",
      "buy"         : "beli",
      "get"         : "dapatkan",
      "unlimited"   : "tidak terbatas",
      "discount"    : "diskon",
      "tap"         : "tekan",
      "hot ice"     : "panas dingin",
      "value range" : "rentang nilai",
      "dear customer" : "pelanggan yang terhormat", 
      "kindly values" : "mohon berikan nilai",
      "your experience at" : "pada pengalaman anda di",
      "service score" : "skor layanan",
      "between"     : "antara",
      "very poor"   : "sangat buruk",
      "to"          : "hingga",
      "excellent"   : "sangat baik",
      "send sms"    : "kirim sms",
      "to free"     : "gratis untuk",
      "for int l charged" : "untuk internasional tanpa dikenakan biaya",
      "store"       : "toko",
      "visit"       : "kunjungi",
      "double"      : "ganda",
      "plus"        : "peningkatan",
      "free member card" : "kartu anggota gratis",
      "high treatment" : "perawatan khusus",
      "gallery"     : "galeri",
      "free doublescoop" : "dua sendok gratis",
      "ice cream"   : "es krim",
      "music streaming" : "penyiaran musik",
      "hot promo"   : "promo terpanas",
      "im spreading" : "saya menyebarkan",
      "the go jek love" : "cinta gojek",
      "at and input" : "dan masukkan",
      "this referral code" : "kode referral ini",
      "to" : "untuk dapatkan rupiah",
      "free credit" : "kredit rupiah gratis",
      "to your first booking gojekgotmehere" : "pada pemesanan pertama Anda kode referral gojekgotmehere",
      "love unduh the go jek" : "unduh gojek",
      "at and input" : "dan masukkan",
      "gojek aplikasi at and input" : "gojek aplikasi dan masukkan",
      "your first booking" : "pada pemesanan pertama anda",
      "referral"    : "referensi",
      "ujiklyakankerjaberstifikat" : "uji kelayakan kerja berstifikat",
      "interview"   : "wawancara",
      "tcashmu"     : "tcash kamu",
      "handphone"   : "telepon genggam",
      "games"       : "permainan",
      "challenge"   : "tantangan",
      "follow"      : "ikuti",
      "gamesmu"     : "permainan kamu",
      "gadget"      : "telepon genggam",
      "pakettelkomselflash" : "paket telkomsel flash",
      "gift"        : "hadiahkan",
      "install"     : "unduh",
      "hot sale"    : "penawaran menarik",
      "trip"        : "perjalanan",
      "combo"       : "kombinasi",
      "discount"    : "diskon",
      "big party weekend" : "akhir pekan pesta besar",
      "dine in take away" : "makan di tempat bawa pulang",
      "may"         : "mei",
      "wib"         : "waktu indonesia barat",
      "t cash"      : "tcash",
      "midnight"    : "tengah malam",
      "t wallet"    : "twallet",
      "sn"          : "nomor seri",
      "website"     : "situs web",
      "restart"     : "muat ulang",
      "non aktifkan" : "tidak aktifkan",
      "non paket"   : "penghentian paket",
      "update"      : "pembaruan",
      "type for english send to free for int l charged": "Ketik 2 untuk bahasa Inggris kirim ke 1166 (GRATIS) (untuk internasional dikenakan biaya)",
      "ri"          : "republik indonesia",
      "non"         : "tidak",
      "game"        : "permainan",
      "heroes"      : "pahlawan",
      "thank you for your appreciation trust in using telkomsel service for further feedback please advice text sms to free for int l charged" : "Terima kasih atas apresiasi dan kepercayaan Anda dalam menggunakan layanan Telkomsel. Untuk umpan balik lebih lanjut, harap beri saran melalui SMS. SMS untuk info (atau informasi) ke nomor gratis, namun biaya mungkin berlaku untuk layanan internasional.",
      "top up coins" : "isi ulang koin",
      "themes"      : "tema",
      "use my invite code and dapatkan a free ride up to redeem it at" : "gunakan kode undangan saya dan dapatkan tumpangan gratis dengan menukarkannya di",
      "kebebasa"    : "kebebasan",
      "streaming"   : "penyiaran",
      "freedom"     : "kebebasan",
      "seleb"       : "selebriti",
      "wa"          : "whatsapp",
      "payment"     : "pembayaran",
      "rate"        : "tarif",
      "mtor"        : "motor",
      "thn"         : "tahun",
      "type"        : "tipe",
      "bb"          : "blackberry",
      "sy"          : "saya",
      "h"           : "haji",
      "intrview"    : "wawancara",
      "dari h darmawan" : "doktor haji darmawan",
      "by hj suri"  : "ibu haji suri",
      "survey"      : "survei",
      "sodara"      : "saudara",
      "a"           : "atas nama",
      "costumer"    : "pelanggan",
      "jend"        : "jenderal",
      "m hubungi"   : "menghubungi",
      "online toko resky discon"  : "daring toko resky diskon",
      "t pilih"     : "terpilih",
      "big sale discound" : "diskon penjualan besar",
      "infohub"     : "info hubungi",
      "discond"     : "diskon",
      "big sal"     : "diskon besar",
      "invite to" : "undang ke",
      "m dapatkan"  : "mendapatkan",
      "copy"         : "salin",
      "survey"      : "survei",
      "y"           : "ya",
      "aplikasi in" : "aplikasi di",
      "google play toko"  : "google play store",
      "for english send" : "untuk bahasa inggris kirim",
      "free for" : "gratis untuk",
      "int l charged"  : "internasional tanpa dikenakan biaya",
      "smartphone"  : "telepon genggam",
      "merchant"    : "pedagang",
      "free internet voice" : "suara internet gratis",
      "merchants partner" : "mitra pedagang",
      "use my invite code" : "gunakan kode undangan saya",
      "and"         : "dan",
      "free ride up"    : "perjalanan gratis",
      "redeem it at" : "tukarkannya di",
      "dscn"        : "diskon",
      "domestic"    : "domestik",    
      "online booking" : "pemesanan online",
      "e ticket"    : "elektronik tiket",
      "e tiket"     : "elektronik tiket",
      "domestic"    : "domestik",
      "gold"        : "emas",
      "hquarters business residence" : "pusat bisnis residensial",
      "prelaunch profit" : "keuntungan prapeluncuran",
      "v"           : "volt",
      "m dapat"     : "mendapat",
      "mngenai"     : "mengenai",
      "new"         : "baru",
      "big sale"    : "diskon besar",
      "online big sal" : "diskon besar online",
      "samsung note ii" : "samsung note",
      "invite"      : "undang",
      "tourch"      : "torch",
      "ktp"         : "kartu tanda penduduk",
      "kk"          : "kartu keluarga",
      "bpkb"        : "buku pemilik kendaraan bermotor",
      "mu"          : "kamu",
      "copy"        : "salin",
      "mobil toyota all"  : "semua mobil toyota",
      "advertising corp" : "perusahaan periklanan",
      "keyword"     : "kata kunci",
      "reg"         : "registrasi",
      "hut"         : "hari ulang tahun",
      "telepon center"  : "pusat telepon",
      "pnjaman"     : "pinjaman",
      "ft cpy"      : "fotokopi",
      "service"     : "layanan",
      "maks"        : "maksimal",
      "limit"       : "batas",
      "counter"     : "loket",
      "see more at" : "lihat lebih lanjut di",
      "tour travel" : "agen perjalanan",
      "discound"    : "diskon",
      "booking"     : "pemesanan",
      "websete"     : "website",
      "merchant"    : "pedagang",
      "one of a million" : "satu dari sejuta",
      "maks"        : "maksimal",
      "delete"      : "hapus",
      "synchronize" : "menyinkronkan",
      "pull"        : "tarik",
      "push"        : "dorong",
      "exhibition"  : "pameran",
      "krna"        : "karena",
      "chat"        : "pesan",
      "sync"        : "sinkronisasi",
      "group"       : "grup",
      "assalamualaikum wr wb" : "assalamualaikum",
      "cpt"         : "cepat",
      "form"        : "formulir",
      "chatnya"     : "pesannya",
      "pa"          : "bapak",
      "softfilenya" : "salinan digitalnya",
      "skrng"       : "sekarang",
      "kasihin"     : "kasih",
      "dmna"        : "dimana",
      "cewe"        : "perempuan",
      "cewek"       : "perempuan",
      "overthink"   : "terlalu banyak berpikir",
      "overreact"   : "bereaksi berlebihan",
      "register"    : "pendaftaran",
      "public"      : "publik",
      "kaka"        : "kakak",
      "machine learningnya"  : "pembelajaran mesinnya",
      "dropdown"    : "menu tarik turun",
      "movie maker" : "pembuat video",
      "something"   : "sesuatu",
      "button"      : "tombol",
      "mock up"      : "model awal",
      "make"        : "pakai",
      "hirenya"     : "perekrutan",
      "take home"   : "bawa pulang",
      "box"         : "kotak",
      "kalo"        : "kalau",
      "weekend"     : "akhir pekan",
      "stay"        : "tinggal",
      "cuss"        : "langsung",
      "meet up"     : "ketemuannya",
      "services"    : "layanan",
      "share"       : "bagikan",
      "birthday"    : "ulang tahun",
      "gnti"        : "ganti",
      "kmn"         : "kemana",
      "level intermediate" : "tingkat menengah",
      "ngebuild"    : "membangun",
      "assalamualaikum wr wb" : "assalamualaikum",
      "level intermediate" : "tingkat menengah",
      "ngebuild"    : "membangun",
      "terima kasih o ya" : "terima kasih ya",
      "route"       : "rute",
      "f copy"      : "fotokopi",
      "project"     : "projek",
      "publish"     : "publikasikan",
      "develop"     : "mengembangkan",
      "hapapa"      : "tidak apa apa",
      "report"      : "laporan",
      "client"      : "klien",
      "scroll up down"  : "gulir ke atas ke bawah",
      "olshop"      : "toko online",
      "device"      : "perangkat",
      "trend"       : "tren",
      "real time"   : "waktu nyata",
      "repository"  : "repositori",
      "multiple choice" : "pilihan ganda",
      "essay"       : "esai",
      "direct link" : "tautan langsung",
      "handycam"    : "kamera genggam",
      "post"        : "unggah",
      "benerin"     : "benarin",
      "backup"      : "cadangan",
      "instal"      : "unduh",
      "code"        : "kode",
      "test"        : "uji",
      "quiz"        : "kuis",
      "diload"      : "dimuat",
      "urgent"      : "mendesak",
      "external"    : "eksternal",
      "case"        : "kasus",
      "salin in"    : "di salin",
      "cash"        : "uang tunai",
      "tranfer"     : "kirim uang",
      "nggk"        : "tidak",
      "eksis l"     : "eksis",
      "iring nya"   : "iringnya",
      "saat nya"    : "saatnya",
      "per bulan"   : "perbulan",
      "nsp nya"     : "nspnya",
      "hatiku nya"  : "hatikunya",
      "gratis nya"  : "gratisnya",
      "mi fi gm mu" : "mi fi giga kamu",
      "kondisi ya"  : "kondisinya",
      "mon hub"     : "mohon hubungi",
      "digantiin"   : "digantikan",
      "kirimin"     : "kirimkan",
      "pembayaran nya" : "pembayarannya",
      "angsur nya"  : "angsurannya",
      "wassalamu alaikum wr wb" : "assalamualaikum",
      "dikirim nya"  : "dikirimnya",
      "disatuin"    : "disatukan",
      "bapak nya"   : "bapaknya",
      "saldo nya"   : "saldonya",
      "ketemu nya"  : " ketemunya",
      "github nya"  : "githubnya",
      "link nya"    : "linknya",
      "instagram nya" : "instagramnya",
      "output nya"  : "outputnya",
      "nilai nya"   : "nilainya",
      "sebelum nya" : "sebelumnya",
      "dorong nya"  : "dorongnya",
      "route nya"   : "rutenya",
      "web nya"     : "webnya",
      "ilmu nya"    : "ilmunya",
      "taqoballahu minna waminkum" : "semoga allah menerima amal ibadah kita dan kamu semua",
      "selamatmenyambutkemenangan" : "selamatmenyambutkemenangan",
      "c nya"       : "c",
      "windows nya" : "windowsnya",
      "harddisk nya" : "harddisknya",
      "kasus nya"   : "kasusnya",
      "salin in"    : "disalin",
      "seengganya"  : "setidaknya",
      "ortu"        : "orang tua",
      "proses nya"  : "prosesnya",
      "mnta"        : "minta",
      "meet up nya" : "ketemuannya",
      "birthday nya"  : "ulang tahunnya",
      "dekstop nya" : "dekstopnya",
      "ilmu nya"    : "ilmunya",
      "case nya"    : "kasusnya",
      "bapak nya"    : "bapaknya",
      "ketemuannya nya" : "ketemuannya",
      "ulang tahun nya" : "ulang tahunnya",
      "rute nya"    : "rutenya",
}

def normalisasi_singkatan(teks):
    kata_kunci = re.compile(r'\b(' + '|'.join(kamus_normalisasi.keys()) + r')\b')

    def ganti_kata(match):
        return kamus_normalisasi[match.group()]

    hasil_normalisasi = kata_kunci.sub(ganti_kata, teks)
    return hasil_normalisasi

# tokenization
def tokenization(teks):
    tokens = word_tokenize(teks)
    return tokens

nltk.download('punkt')
nltk.download('stopwords')

def remove_stopwords(teks):
    stop_words = set(stopwords.words('indonesian'))
    filtered_text = [word for word in teks if word not in stop_words]
    return filtered_text

# stemming
factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stemming(teks):
    stemmed_words = [stemmer.stem(word) for word in teks]
    return stemmed_words

def tfidf(data):
    tf = TfidfVectorizer()
    text_tf = tf.fit_transform(data["teks"].astype("U"))
    return text_tf

# SMOTE
def smote(X_train, y_train):
    sm = SMOTE(random_state=2)
    X_train_res, y_train_res = sm.fit_resample(X_train, y_train)
    return X_train_res, y_train_res

def smoteMiSVM(c,X_train_res,y_train_res,X_test,y_test, threshold = 0.07):

    #Mutual Information
    mutual_information = mutual_info_classif(X_train_res, y_train_res)
    selected_features_indices = [idx for idx, mi in enumerate(mutual_information) if mi > threshold]
    print("selected features indices :", selected_features_indices)
    selected_features_X_train_res = X_train_res[:, selected_features_indices]
    selected_features_X_test = X_test[:, selected_features_indices]
    X_test_for_prediction = selected_features_X_test 
         
    # SVM training
    clf = svm.SVC(kernel='linear', C=c).fit(selected_features_X_train_res, y_train_res)

    y_pred = clf.predict(X_test_for_prediction)

    return y_pred

def smoteSVM(c,X_train_res, y_train_res,X_test,y_test):
    
    clf = svm.SVC(kernel='linear', C=c).fit(X_train_res, y_train_res)

    y_pred = clf.predict(X_test)
    return y_pred
